dist: bionic

language: node_js

node_js:
  - 12

stages:
 - name: prepare
   if: branch != master
 - name: publish

cache: yarn

jobs:
  include:
    - stage: prepare
      script:
      - npm config set registry https://npm.pkg.github.com/deviceinsight
      - yarn install

    - stage: publish
      if: tag IS present
      name: travis ci
      script:
      - npm config set registry https://npm.pkg.github.com/deviceinsight
      - echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}'>.npmrc
      - yarn publish

    - stage: publish
      if: branch = develop
      script:
      - npm config set registry https://npm.pkg.github.com/deviceinsight
      - echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}'>.npmrc
      - npm publish --tag next
