dist: bionic

language: node_js

node_js:
  - 12

stages:
 - name: prepare
   if: NOT (branch = master)
 - name: publish

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: prepare
      #install:
      script:
      - npm config set registry https://npm.pkg.github.com/deviceinsight
      - yarn install

    - stage: publish
      if: tags
      name: travis ci
      script:
      - npm config set registry https://npm.pkg.github.com/deviceinsight
      - echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}'>.npmrc
      - yarn publish

    - stage: publish
      if: branch = develop
      script:
      - npm config set registry https://npm.pkg.github.com/deviceinsight
      - echo '//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}'>.npmrc
      - npm publish --tag next
