dist: bionic

language: node_js

node_js:
  - 12

stages:
 - name: publish

cache: yarn

jobs:
  include:
    - stage: publish
      #if: tag IS present
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        #on:
        #  tags: true